### ISSUE TITLE
create assets folder to organize other files

### ISSUE THREAD

**Issue by vinzvinci** [rohank2502/EddieHub_Members#2]
I think it's better if other files like `css`, `img`  organize from `assets` folder.  The cleaner, the better.
```
- assets > css
- assets > img
- assets > js `(if ever there's javascript)`
```

**Comment by rohan-kulkarni-25** [comment]
True !! Will you like to go for it or It was a suggestion ?

**Comment by vinzvinci** [comment]
Can't do it right now. Maybe add a label `good first issue` and `enhancement`? Then share it at **EddieHub** discord server... in `Community Discussion category` and in `good-first-issues` section (this is better, you will help people to get green square)
