### ISSUE TITLE
add tags and website link at about section

### ISSUE THREAD

**Issue by vinzvinci** [rohank2502/EddieHub_Members#5]
About section:
- Add short description like `EddieHub Community Members repository`
- Add the website link

Add tags:
- html, css, community

<hr /> 

`screenshot`
![about](https://user-images.githubusercontent.com/73097560/112848567-cce8a100-90da-11eb-93bc-b022d90ce2e7.png)

**Comment by rohan-kulkarni-25** [comment]
Ok will give this for Good first issue

**Comment by rohan-kulkarni-25** [comment]
Done !
