### ISSUE TITLE
remove email info.

### ISSUE THREAD

**Issue by vinzvinci** [rohank2502/EddieHub_Members#6]
**GitHub**, **Twitter**, **Instagram** is enough. Don't include email, we avoid spammers. 

better swap `gmail` to `instagram`

Safety first.

**Comment by rohan-kulkarni-25** [comment]
> **GitHub**, **Twitter**, **Instagram** is enough. Don't include email, we avoid spammers.
> 
> better swap `gmail` to `instagram`
> 
> Safety first.

Yes we can do that !! I will add Instagram in place of Gmail
