### ISSUE TITLE
Bug on mobile view 

### ISSUE THREAD

**Issue by schmelto** [rohank2502/EddieHub_Members#7]
![Screenshot_20210330_032914_com.android.chrome.jpg](https://user-images.githubusercontent.com/30869493/112919868-2f0bcb00-9108-11eb-88c2-7d8177f6ba83.jpg)

**Comment by rohan-kulkarni-25** [comment]
Yes actually this is because i used left float for the box but I don't see any other option for making the boxes float please if u have any do changes

**Comment by rohan-kulkarni-25** [comment]
@schmelto  Please add your profile too
