### ISSUE TITLE
Add github pages link to About section

### ISSUE THREAD

**Issue by schmelto** [rohank2502/EddieHub_Members#9]
![image](https://user-images.githubusercontent.com/30869493/113010826-70888e80-9179-11eb-8b09-efd684048f17.png)

**Comment by rohan-kulkarni-25** [comment]
Yes that is cool Idea !

**Comment by Ektagautammaru** [comment]
will you assign me this work 
I am eagar to do this work

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> will you assign me this work
> I am eagar to do this work

Nice to see your excitement @Ektagautammaru

**Comment by rohan-kulkarni-25** [comment]
@Ektagautammaru  I have assigned you this issue and will like to tell you exactly what you have to do as this is good first issue 

Click on the settings icon near the about in top right section one tab will open in that tab in website section you have to paste the website and create a pull request don't forget to star fork and clone the project and then make changes 

`https://rohank2502.github.io/EddieHub_Members/`

**Comment by rohan-kulkarni-25** [comment]
Done This !
